Algoritmo "10"

Var
fabrica, valor3, valor1, valor2:Real
porcdist, imposto:Inteiro

Inicio
Escreval("Informe o valor de fábrica de seu carro: ")
Leia(fabrica)
Escreval("Informe a porcentagem do distribuidor: ")
Leia(porcdist)
Escreval("Informe a porcentagem de impostos: ")
Leia(imposto)
valor1<-(fabrica*porcdist/100)
valor2<-(fabrica*imposto/100)
valor3<-fabrica+Valor1+Valor2)
Escreval("Valor de seu carro: R$ ", valor3)

Fimalgoritmo