Algoritmo "11"

Var
salariofixo, totalvendas, carrosvendidos, comissao, salariofinal, v1 : real

Inicio
Escreval("Informe o salário fixo: ")
Leia(salariofixo)
Escreval("Informe o total de vendas: R$ ")
Leia(totalvendas)
Escreval("Informe o número de carro vendidos: ")
Leia(carrosvendidos)
Escreval("Informe a comissão: R$ ")
Leia(comissao)
salariofinal<-(carrosvendidos*v1)+(totalvendas*5/100)+salariofixo
Escreval("Salário final: R$ ",salariofinal)

Fimalgoritmo